name: Manual
env:
  CI: true
  FORCE_COLOR: 1
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
on:
  workflow_dispatch:
    inputs:
      metamask-tag:
        description: 'Tag of metamask to download. ie. "v10.27.0"'
      metamask-seed:
        description: 'Seed to use for metamask'
      metamask-password:
        description: 'Password to use for metamask'
      metamask-snap-id:
        description: 'Snap ID to use for metamask. ie. "npm:@chainsafe/filsnap"'
      metamask-snap-version:
        description: 'Snap version to use for metamask'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx playwright install chromium --with-deps
      - run: pnpm -r --filter testing run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
