name: Tools
env:
  CI: true
  FORCE_COLOR: 1
  # PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
  # PLAYWRIGHT_BROWSERS_PATH: 0
on:
  push:
    branches:
      - main
    paths:
      - 'packages/tools/**'
      - '.github/workflows/tools.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/tools/**'
      - '.github/workflows/tools.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r --filter filsnap-testing-tools run lint
      # - run: pnpm dlx playwright install --with-deps chromium
      - run: pnpm -r --filter filsnap-testing-tools run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: pnpm -r --filter filsnap-testing-tools exec depcheck
