name: Tools
env:
  CI: true
  FORCE_COLOR: 1
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
on:
  push:
    branches:
      - main
    paths:
      - 'packages/tools/**'
      - '.github/workflows/tools.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/tools/**'
      - '.github/workflows/tools.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter metamask-testing-tools run lint
      - run: pnpm -r --filter metamask-testing-tools exec depcheck
      - run: pnpm exec playwright install
      - run: pnpm -r --filter metamask-testing-tools run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
